- name: slow
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: sh
      args:
        - get-token.sh
- name: cache
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kcc-cache
      args:
        - sh
        - get-token.sh
