# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - &build
    id: kcc-cache
    binary: kcc-cache
    main: ./cmd/kcc-cache
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - <<: *build
    id: kcc-injector
    binary: kcc-injector
    main: ./cmd/kcc-injector
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  draft: true
  prerelease: auto
