name: asdf-lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v3

      - name: Run ShellCheck
        run: bin/scripts/shellcheck.bash

  shellfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v3

      - name: List file to shfmt
        run: shfmt -f .
